import { readableDate } from "@/helpers";

export const featurePropertiesCard = [
  {
    property: "constellation",
    name: "Constellation",
    info: "The group of satellites that the platform belongs to.",
  },
  {
    property: "platform",
    name: "Platform",
    info: "Identifies the satellite or sensor platform that captured the data, providing context on the source of the observation.",
  },
  {
    property: "start_datetime",
    name: "Start DateTime",
    info: "The date and time when the observation began, serving as a temporal reference for the captured data.",
  },
  {
    property: "eo:cloud_cover",
    name: "Cloud coverage",
    info: "Indicates the percentage of the area covered by clouds, which can significantly impact the quality and usability of the data.",
  },
];

export const featuresModal = [
  {
    property: "platform",
    name: "Platform",
    info: "Identifies the satellite or sensor platform that captured the data, providing context on the source of the observation.",
  },
  {
    property: "start_datetime",
    name: "Start DateTime",
    info: "The date and time when the observation began, serving as a temporal reference for the captured data.",
  },
  {
    property: "eo:cloud_cover",
    name: "Cloud coverage",
    info: "Indicates the percentage of the area covered by clouds, which can significantly impact the quality and usability of the data.",
  },
  {
    property: "sar:frequency_band",
    name: "Frequency Band",
    info: "Specifies the frequency band used by the Synthetic Aperture Radar (SAR), crucial for understanding the type of data and its applications.",
  },
  {
    property: "sar:center_frequency",
    name: "Center Frequency",
    info: "Refers to the central frequency of the SAR, providing insights into the resolution and detail level of the radar data.",
  },
  {
    property: "sar:observation_direction",
    name: "Observation Direction",
    info: "Describes the direction in which the sensor was pointing during data collection, which can influence data interpretation.",
  },
  {
    property: "sar:instrument_mode",
    name: "Instrument Mode",
    info: "Indicates the operating mode of the SAR instrument, which can affect the type and quality of the data collected.",
  },
  {
    property: "sar:polarizations",
    name: "Polarizations",
    info: "Lists the polarization states of the radar signals, offering different perspectives on the observed surface properties.",
  },
  {
    property: "sar:product_type",
    name: "Product Type",
    info: "Identifies the specific SAR product, such as GRD (Ground Range Detected), which indicates the processing level of the data.",
  },
  {
    property: "proj:epsg",
    name: "EPSG",
    info: "The EPSG code that defines the coordinate reference system used for spatially referencing the data on Earth's surface.",
  },
  {
    property: "proj:centroid",
    name: "Centroid",
    info: "The geographic center point of the feature, often used for mapping or as a representative location.",
  },
  {
    property: "s1:processing_datetime",
    name: "Processing Datetime",
    info: "The date and time when the data was processed, providing insight into the timeliness and currency of the information.",
  },
  {
    property: "datetime",
    name: "Date and Time of Observation",
    info: "The specific date and time when the data was captured. Important for temporal analysis and understanding the conditions at the time of capture.",
  },
  {
    property: "view:sun_azimuth",
    name: "Sun Azimuth",
    info: "The angle between the north direction and the sun, measured clockwise. It helps in understanding the lighting conditions during the capture.",
  },
  {
    property: "view:sun_elevation",
    name: "Sun Elevation",
    info: "The angle of the sun above the horizon. This affects shadow lengths and can influence the interpretation of the imagery.",
  },
  {
    property: "view:sun_elevation",
    name: "Sun Elevation",
    info: "The angle of the sun above the horizon. This affects shadow lengths and can influence the interpretation of the imagery.",
  },
  {
    property: "grid:code",
    name: "MGRS Grid Code",
    info: "The Military Grid Reference System (MGRS) code, providing a precise location reference within the grid.",
  },
  {
    property: "s2:product_type",
    name: "Product Type",
    info: "The type of product generated by the sensor, such as S2MSI2A, which indicates a specific processing level of the Sentinel-2 data.",
  },
  {
    property: "s2:processing_baseline",
    name: "Processing Baseline",
    info: "The baseline version used for processing the data, which can help in identifying the processing standards applied.",
  },
  {
    property: "s2:nodata_pixel_percentage",
    name: "No Data Pixel Percentage",
    info: "The percentage of pixels in the data that contain no information. Important for assessing the completeness of the dataset.",
  },
  {
    property: "s2:reflectance_conversion_factor",
    name: "Reflectance Conversion Factor",
    info: "A factor used to convert the pixel values to reflectance, important for quantitative analysis of the imagery.",
  },
];

export function formatValue(value: any): string {
  if (value === null || value === undefined) {
    return "N/A";
  }
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  if (typeof value === "string" && !isNaN(Date.parse(value))) {
    return readableDate(value);
  }
  if (typeof value === "object") {
    return Object.entries(value)
      .map(([key, val]) => `${key}: ${val}`)
      .join(", ");
  }
  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  if (typeof value === "number") {
    return value.toFixed(2).toString();
  }
  return String(value);
}
